# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('age', models.DecimalField(decimal_places=0, max_digits=2)),
                ('bill_in_day', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
